// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx ts-node prisma/seed.ts',
  },
  datasource: {
    // Migrations run over the direct/session-mode connection (pgbouncer
    // transaction pooling can't hold the advisory locks Migrate needs).
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
